services:
  - type: web
    name: duty-fangkham
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
